### ISSUE TITLE
Figure out a recommended tracking system for data science workflow

### ISSUE THREAD

**Issue by karenng-civicsoftware** [hackoregon/2019HackORDataScienceTemplate#8]
- [ ] read up on [DVC](https://dvc.org/)
- [ ] read up on [ML flow](http://mlflow.org/)
- [ ] read up on [Pachyderm](https://pachyderm.io/index.html)

- [ ] recommend the best solution
